services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: wasmbox
      POSTGRES_PASSWORD: wasmbox
      POSTGRES_DB: wasmbox
    ports:
      - "5433:5432"
    volumes:
      - wasmbox_pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wasmbox"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    restart: unless-stopped
    profiles:
      - full

  compiler:
    build:
      context: ./compiler
    image: wasmbox-compiler:local
    profiles:
      - compile
    volumes:
      - ./artifacts:/artifacts

  prometheus:
    image: prom/prometheus:v2.54.1
    ports:
      - "9091:9090"
    volumes:
      - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./infra/alerts.yml:/etc/prometheus/alerts.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.3.0
    ports:
      - "3002:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  wasmbox_pg_data:
